server:
  port: 10086
spring:
  datasource:
    username: root
    password: 123456
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000

