server:
  port: 10086
spring:
  datasource:
    username: root
    password: pengfeng
    url: jdbc:mysql://47.100.206.217:3306/mysql?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource