server:
  port: 10086
spring:
  datasource:
    username: root
    password: iloveu
    url: jdbc:mysql://47.100.206.217:3308/threadpool?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource

task:
  pool:
   corePoolSize: 20
   maxPoolSize: 40
   keepAliveSeconds: 300
   queueCapacity: 50
